language: perl
before_install:
  - (cd java && ./travis-install.sh)
before_cache:
  - mkdir -p $HOME/.cache/jar
  - cp java/*.jar $HOME/.cache/jar
cache:
  directories:
    - $HOME/.cache/jar
perl:
  - "5.22"
  - "5.20"
  - "5.18"
  - "5.16"
  - "5.14"
  - "5.12"
  - "5.10"
