---
abstract: 'The great new Barcode::PDF417!'
author:
  - 'Andrea Nall <anall@andreanall.com>'
build_requires: {}
configure_requires:
  Module::Build: '0.4003'
dynamic_config: 1
generated_by: 'Module::Build version 0.4003, CPAN::Meta::Converter version 2.133380'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Barcode-PDF417
provides:
  Barcode::PDF417:
    file: lib/Barcode/PDF417.pm
    version: '0.01'
  Barcode::PDF417::PP:
    file: lib/Barcode/PDF417/PP.pm
  Barcode::PDF417::PP_Tables:
    file: lib/Barcode/PDF417/PP_Tables.pm
requires:
  IO::File: '0'
  Test::Exception: '0'
  Test::More: '0'
resources:
  license: http://www.perlfoundation.org/artistic_license_2_0
version: '0.01'
